config/routes.rb
BtlTomskNarujka::Application.routes.draw do

  get '/blog' => "posts#index", as: :posts
  get '/blog/:slug' => "posts#show", as: :post

  get '/yslygi' => "services#index", as: :services
  get '/yslygi/:slug' => "services#show", as: :service

  resources :portfolio, only: [:index, :show]
  resources :contacts,  only: [:index]
  resources :orders,    only: [:create]

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
end

app/models/action.rb
# coding: utf-8

class Action < ActiveRecord::Base

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attacheble, polymorphic: true

  has_attached_file :attach, styles: {small: '314x157#', gallery: '1024x768<'}
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :service
  has_many   :attachments, as: :attacheble
  accepts_nested_attributes_for :attachments, allow_destroy: true
end

app/models/order.rb
# coding: utf-8

class Order < ActiveRecord::Base
  belongs_to :service

  validates :name, :phone, presence: true

  after_save :send_message

private

  def send_message
    Smsru::Sender.sms_send('79539237396', "Новый заказ: #{self.name} #{self.phone}")
  end
end

app/models/post.rb
# coding: utf-8

class Post < ActiveRecord::Base
  has_many :attachments, as: :attacheble
  accepts_nested_attributes_for :attachments, allow_destroy: true

  acts_as_taggable
  acts_as_taggable_on :tags

  default_scope order('created_at DESC')
end

app/models/service.rb
# coding: utf-8

class Service < ActiveRecord::Base
   has_many :items
   has_many :orders
   has_many :attachments, as: :attacheble
   accepts_nested_attributes_for :attachments, allow_destroy: true

   has_attached_file :icon, styles: {small: '100x100'}

   default_scope { order('priority') }

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_attached_file :photo, styles: {slide: "942x315#"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :new_order

  def new_order
    @order = Order.new
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @order = Order.new
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  def index
    @slides = Slide.all
    @items = Item.order('id desc').limit(6)
  end
end

app/controllers/orders_controller.rb
# coding: utf-8

class OrdersController < ApplicationController
  def create
    @order = Order.new(permitted_params)
    if @order.save
      redirect_to request.referer
      flash[:notice] = "Ваш заказ успешно отправлен"
    else
      redirect_to request.referer
      flash[:error]  = "Не удалось отправить заказ"
    end
  end

  private

  def permitted_params
    params.require(:order).permit(:name, :email, :phone, :service_id, :message )
  end
end

app/controllers/portfolio_controller.rb
# coding: utf-8

class PortfolioController < ApplicationController
  def index
    @items = Item.order('id desc')
  end

  def show
    @items = Item.where(service_id: params[:id])
  end
end

app/controllers/posts_controller.rb
# coding utf-8

class PostsController < ApplicationController

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find_by_slug(params[:slug])
  end
end

app/controllers/services_controller.rb
# coding: utf-8

class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find_by(slug: params[:slug])
    @order = Order.new
  end
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper

  def meta_title(title)
    content_for :meta_title do
      title
    end
  end

  def meta_keywords(title)
    content_for :meta_keywords do
      title
    end
  end

  def meta_description(title)
    content_for :meta_description do
      title
    end
  end

  def render_flash_notice
    out = ''
    if flash[:notice]
      out += "<div class='flash-notice'>#{flash[:notice]}</div>"
    elsif flash[:error]
      out += "<div class='flash-error'>#{flash[:error]}</div>"
    end
    raw out
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/posts/_tags.html.erb
<div class="vg-item-article a-left vg-btn-height">
  <h3 class="vg-categories-icon vg-margin-1">Облако тэгов</h3>
  <ul id="tag_cloud">
    <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
        <li><%= link_to tag.name, posts_path(tag: tag.name), class: css_class %></li>
    <% end %>
  </ul>
</div>

app/views/posts/index.html.erb
<%= meta_title("Блог о наружной рекламе и маркетинге | ProstOR, Томск ") %>
<%= meta_description("Что такое наружная реклама? Как наружная реклама помогает бизнесу? Подписывайся и читай, узнай все самое интересное о наружке :)") %>
<%= meta_keywords("Наружка, блог, статьи о рекламе, реклама в Томске") %>

<%= content_for :header do %>
    <div class="vg-aboutus-text">
      <div class="vg-header">Блог о рекламе</div>
      <p class="header-text">
        На этой странице Вас ждут последние статьи, новости, обзоры из области наружной рекламы,
        бизнеса и маркетинга.
      </p>
    </div>
<% end %>

<article class="border-top c-two vg-left-bar vg-table-display vg-blog-bar">
  <%= render 'tags' %>
  <div class="vg-item-article a-left vg-btn-height">
    <h3 class="vg-categories-icon vg-margin-1">Категории услуг</h3>
    <% Service.all.each do |service| %>
        <a href="<%= service_path service.slug %>" class="vg-page">
          » <%= service.title %>
        </a>
    <% end %>
  </div>

  <%= render 'shared/social_sidebar' %>
</article>

<article class="border-top border-left c-four vg-table-display vg-blog-posts">
  <% @posts.each do |post| %>
      <article class="border-top c-two vg-intro-post">
        <div style="margin: 40px 15px;" class="vg-item-article a-right">
          <a href="<%= post_path(post.slug) %>">
            <img src="<%= post.attachments.first.attach.url(:small) if post.attachments.any? %>" height="52" width="60" style="padding: 3px;
                    background: #0BBCD3;">
          </a>
          <h3>
            <a href="<%= post_path(post.slug) %>"><%= post.title %></a>
          </h3>
          <div class="vg-subtitle">
            <br/><span style="font-size: 13px; font-style: italic;"><%= Russian::strftime(post.updated_at, "%d %B %Y") %></span>
            <!--<a href="/portfolio/<%#= post.id %>"><span class="vg-icon">→</span>В портфолио</a>-->
            <div class="post-tags-i">
              <span>Тэги: </span><%= raw post.tag_list.map {|tag| link_to tag, posts_path(tag: tag) }.join(", ") %>
            </div>
          </div>
        </div>
      </article>
      <article class="border-top c-two vg-overflow vg-margin-2" >
        <div class="vg-item-article" >
          <p class="vg-intro-text">
            <%= post.summary %><br/><br/>

            <a href="<%= post_path(post.slug) %>" class="vg-readmore f-right">
              Читать далее <span class="vg-icon">→</span></a>
          </p>
        </div>
      </article>
  <% end %>
</article>

app/views/posts/show.html.erb
<%= content_for :head do %>
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?102"></script>
    <script type="text/javascript">
        VK.init({apiId: 3998134, onlyWidgets: true});
    </script>
<% end %>

<%= meta_title(@post.meta_title) %>
<%= meta_description(@post.meta_description) %>
<%= meta_keywords(@post.meta_keywords) %>

<%= content_for :header do %>
    <div class="vg-aboutus-text">
      <div class="vg-header"><%= @post.title %></div>
      <p class="header-text">
        <%= @post.summary %>
      </p>
    </div>
<% end %>

<article class="border-top c-two vg-left-bar vg-table-display vg-blog-bar">
  <%= render 'tags' %>
  <div class="vg-item-article a-left vg-btn-height">
    <h3 class="vg-categories-icon vg-margin-1">Категории услуг</h3>
    <% Service.all.each do |service| %>
        <a href="<%= service_path service.slug %>" class="vg-page">
          » <%= service.title %>
        </a>
    <% end %>
  </div>

  <%= render 'shared/social_sidebar' %>
</article>

<article class="border-top border-left c-four vg-table-display vg-blog-posts">
  <div class="content-body"><%= raw @post.body %></div>
  <div class="after-topic">
      <div class="tags">
        <span>Тэги: </span><%= raw @post.tag_list.map {|tag| link_to tag, posts_path(tag) }.join(", ") %>
      </div>
      <div class="likes">
          <div id="vk_like"></div>
          <script type="text/javascript">
              VK.Widgets.Like("vk_like", {type: "button"});
          </script>
      </div>
      <div class="likes">
        <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
      </div>
    <div class="clearfix"></div>
  </div>
  <div class="clearfix"></div>
  <div id="vk_comments"></div>
  <script type="text/javascript">
      VK.Widgets.Comments("vk_comments", {limit: 5, width: "520", attach: "*"});
  </script>
  <div class="clearfix"></div>
</article>

app/views/services/index.html.erb
<%= meta_title("Услуги по производству наружной рекламы | POSTER") %>
<%= meta_description("Стенды, таблички, штендеры, фотобаннеры и многое другое! Мы создаем качественную рекламу для Вас!") %>
<%= meta_keywords("стенды, таблички, штендеры, фотобаннеры, роллапы, ремонт рекламы") %>

<%= content_for :header do %>
    <div class="vg-aboutus-text">
      <div class="vg-header">Услуги</div>
      <p class="header-text">
        Ниже представлен список услуг нашей компании по производству рекламных материалов.
        Если Вам нужны стенды, таблички, стойки, пресс-воллы, брендирование, то Вы по адресу!
      </p>
    </div>
<% end %>

<article class="border-top c-two vg-left-bar vg-table-display vg-blog-bar">
    <%= render 'shared/social_sidebar' %>
</article>


<article class="border-top border-left c-four vg-table-display vg-blog-posts">
  <% @services.each do |service| %>
      <article class="border-top c-two vg-intro-post">
        <div class="vg-item-article a-right">
          <a href="<%= service_path(service.slug) %>">
          <img src="<%= service.icon.url if service.icon %>" height="42" width="50" style="padding: 10px;
                  background: #0BBCD3;">
          </a>
          <h3>
            <a href="<%= service_path(service.slug) %>"><%= service.title %></a>
          </h3>
          <div class="vg-subtitle">
            <!--<a href="/portfolio/<%#= service.id %>"><span class="vg-icon">→</span>В портфолио</a>-->
          </div>
        </div>
      </article>
      <article class="border-top c-two vg-overflow vg-margin-2">
        <div class="vg-item-article">
          <p class="vg-intro-text">
            <%= service.summary %><br/><br/>

            <a href="<%= service_path(service.slug) %>" class="vg-readmore f-right">
              Перейти <span class="vg-icon">→</span></a>
          </p>
        </div>
      </article>
  <% end %>
</article>

app/views/services/show.html.erb
<%= meta_title(@service.meta_title) %>
<%= meta_description(@service.meta_description) %>
<%= meta_keywords(@service.meta_keywords) %>

<%= content_for :header do %>
<div class="vg-aboutus-text">
  <div class="vg-header"><%= @service.title %></div>
  <p class="header-text">
    <%= @service.summary %>
  </p>
  <a href="#orderform" class="vg-link-button-big">Заказать<span class="vg-icon">→
    </span></a>
</div>
<% end %>


<article class="border-top c-two vg-left-bar vg-table-display vg-blog-bar">
  <div class="vg-item-article a-left vg-btn-height">
    <h3 class="vg-categories-icon vg-margin-1">Категории услуг</h3>
    <% Service.all.each do |service| %>
        <a href="<%= service_path service.slug %>" class="vg-page">
          » <%= service.title %>
        </a>
    <% end %>
  </div>

  <%= render 'shared/social_sidebar' %>
</article>

<article class="border-top border-left c-four vg-table-display vg-blog-posts">
  <div class="content-body"><%= raw @service.body %></div>

  <% if @service.attachments.any? %>
    <h2>Примеры</h2>
    <div class="content-page-images">
    <% @service.attachments.each do |at| %>
        <article class="border-left border-bottom border-top c-two vg-portfolio-item"
                 style="background-image:url(<%= at.attach.url(:small) %>)">
          <div class="vg-background" style="opacity: 0;">
            <h4>
              <a class="fancy"  href="<%= at.attach.url(:gallery) %>" style="color:#fff;"><%= at.title %></a>
            </h4>
            <div class="vg-subtitle a-center">

            </div>

            <p class="vg-port">
              <a class="fancy" rel="gallery" href="<%= at.attach.url(:gallery) %>">
                Посмотреть
            <span class="vg-icon">→
            </span>
              </a>
            </p>
          </div>
        </article>
    <% end %>
  </div>
  <% end %>
  <div class="clearfix"></div>
  <div class="content-body order" id="orderform">
    <h2 style="padding: 0px;">Оформить заказ</h2>
    <%= form_for @order do |f| %>
        <% @order.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <%= f.hidden_field :service_id, :value => @order.id %>
        <div class="main-order-fields">
          <%= f.label :name, "Ваше Имя*" %><br/>
          <%= f.text_field :name %>
        </div>
        <div class="main-order-fields">
          <%= f.label :phone, "Ваш телефон*" %><br/>
          <%= f.text_field :phone %>
        </div>
        <div class="main-order-fields">
          <%= f.label :email, "Ваш E-mail" %><br/>
          <%= f.text_field :email %>
        </div>
        <div class="clearfix"></div>
        <div class="order-textarea">
          <%= f.label :message, "Сообщение" %> <br/>
          <%= f.text_area :message %>
        </div>
        <%= f.submit "→ Заказать", class: "vg-link-button-big-2" %>
    <% end %>
  </div>

</article>